### ISSUE TITLE
No icon

### ISSUE THREAD

**Issue by gaveer** [Dadum/LFClean#2]
![image](https://user-images.githubusercontent.com/45834601/118417664-d72c2200-b6bd-11eb-8d9e-4f72ab4ce076.png)

**Comment by gaveer** [comment]
![image](https://user-images.githubusercontent.com/45834601/118417692-f034d300-b6bd-11eb-9150-854ad120a925.png)

**Comment by gaveer** [comment]
**after 2x press Entry Button on config**
![image](https://user-images.githubusercontent.com/45834601/118417774-4bff5c00-b6be-11eb-8d0a-3f010dc546e7.png)

**Comment by gaveer** [comment]
Have the following addon 
- WorldquestTracker
- PremadeFilter

**Comment by gaveer** [comment]
![image](https://user-images.githubusercontent.com/45834601/118417821-849f3580-b6be-11eb-852a-b30bcc85ac98.png)

**Comment by Dadum** [comment]
@gaveer thanks a lot for the details! From a very early look there seems to be some silent clashing with `PremadeFilter` (no errors are thrown, but the buttons or icons won’t always load properly). I'm looking into it.

**Comment by Dadum** [comment]
@gaveer looking a bit into it I see two main problems:
* The entry button toggle is actually broken and doesn't correctly handle how the buttons are getting rid of when toggling it. This causes the icon to black out after a couple of times it gets toggled due to frames stacking up. That's quite an easy fix (already available on the beta channel of the addon).
* The buttons don't show up at all when `LFClean` exists together with `PremadeFilter`, and they do not properly update if forcefully generated through toggling the config option. This seems more of a problem with the latter addon completely overriding the `LFGListSearchPanel_UpdateResults` function and thus disallowing any other addon to properly hook to it. This seems quite a headache to work around but I'll try to cook up something. Meanwhile I'd suggest also opening an issue on the matter for `PremadeFilter`.
